version: "3"

services:
  db:
    image: mysql:latest
    volumes:
      - ./mysql-settings:/etc/mysql/conf.d
      - ~/django-edge-mysql/django-db/db-data:/var/lib/mysql
    env_file:
      - db-variables.env

  web:
    # https://github.com/Drunkar/dockerfiles/tree/master/anaconda-django-edge
    image: drunkar/anaconda-django-edge-mysql
    volumes:
      - ~/django-edge-mysql/django-edge:/usr/src/app
    ports:
      - "8000:8000"
    links:
      - db:db
    environment:
      - DB_PORT_3306_TCP_ADDR=db
    env_file:
      - db-variables.env
